POST http://localhost:4004/odata/v4/inv-catalog/InvCatalogService.postInvoice
Content-Type: application/json

{
    "documentNumber": "5000000010",
    "netAmount": "$ 1600.00",
    "taxId": "12-5846832",
    "taxName": "Sales Tax:",
    "purchaseOrderNumber": "4500000011",
    "grossAmount": "$ 1600.00",
    "currencyCode": "CAD",
    "receiverContact": "Curtis V. Brown",
    "documentDate": "2025-02-05",
    "taxAmount": "$ 0.00",
    "taxRate": "0.0",
    "receiverName": "Standard Products",
    "receiverAddress": "3150 SW 9th Street Toronto, ON L5V 1X2 CANADA",
    "paymentTerms": "Due upon receipt",
    "senderAddress": "3451 NE Willoughby Blvd. Sturt, ON LV5 1X2 CANADA",
    "senderName": "Alfreds Futterkiste",
    "senderMail": "jibin.thomas@msitek.us",
    "dmsFolder": "spa-res:cmis:folderid:feyrjry4cjqnbRuTvf0lG0GK-WoHhlw4zz5whTJiIOM",
    "to_Item": [
        {
            "description": "Professional Service",
            "netAmount": "1600.00",
            "quantity": "100.00",
            "unitPrice": "16.00",
            "materialNumber": "2001",
            "unitOfMeasure": "PC"
        }
    ]
}

### empty object
POST http://localhost:4004/odata/v4/inv-catalog/MediaFile
Content-Type: application/json

{}

### Upload Document Test
PUT http://localhost:4004/odata/v4/inv-catalog/MediaFile(a8d2d638-c156-48c3-b1f9-5f1be40a9a2d)/content
Content-Type: application/pdf
slug: alfreds invoice.pdf

< ./alfreds invoice.pdf